Se actualizó el pipeline de github actions para aumentar el tiempo de espera a la DB, se agregó bloque finally al try catch, para cerrar la conección luego de intentar conectar a la DB

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -21,7 +21,7 @@ jobs:
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
         options: >-
-          --health-cmd="pg_isready -U postgres"
+          --health-cmd="pg_isready -U postgres -d mabc_cv_test" # Mejorar health check
           --health-interval=10s
           --health-timeout=5s
           --health-retries=5
@@ -52,12 +52,17 @@ jobs:
 
       - name: Esperar que PostgreSQL esté listo
         run: |
-          for i in {1..30}; do
-            nc -z localhost 5433 && echo "PostgreSQL está listo" && exit 0
-            echo "Esperando PostgreSQL..."
-            sleep 5
-          done          
-          echo "PostgreSQL no respondió" && exit 1
+          echo "Esperando que PostgreSQL esté listo en el puerto 5433..."
+          for i in {1..60}; do
+            if pg_isready -h localhost -p 5433 -U postgres -d mabc_cv_test; then
+              echo "PostgreSQL está listo."
+              exit 0
+            fi
+            echo "PostgreSQL aún no está listo. Reintentando en 1 segundo..."
+            sleep 1
+          done
+          echo "Error: PostgreSQL no se inició a tiempo."
+          exit 1
 
       - name: Ejecutar tests unitarios
         run: cd backend-cv && npm run test:unit
